id: IFDF0E60C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T23:55:48+00:00'
last_modified: '2022-06-09T04:29:24.947062+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016290
  title: སྤྱོད་པ་བསྡུས་པའི་སྒྲོན་མེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    24B0:
      image_group_id: I00JW501195
      title: Volume 1 of spyod pa bsdus pa'i sgron me the caryamelapakapradipa of
        aryadeva
      total_pages: 452
      order: 1
      base_file: 24B0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
