id: P008099
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 13:01:28.975467
source_metadata:
  id: bdr:W00EGS1016290
  title: སྤྱོད་པ་བསྡུས་པའི་སྒྲོན་མེ།
  author: ''
  volumes:
    2e8420d5147c400e9cc5614a929fa869:
      image_group_id: I00JW501195
      title: Volume 1 of spyod pa bsdus pa'i sgron me the caryamelapakapradipa of
        aryadeva
      volume_number: 1
      total_pages: 452
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
